GET http:localhost:5000/references

### → this "###" separate 2 requests, otherwise it will be considered as one and just one link will appear
POST http://localhost:5000/references/add 
Content-type:application/json
