{
    "title":"React - The Complete Guide (incl Hooks, React Router, Redux)", 
    "link": "https://www.udemy.com/course/react-the-complete-guide-incl-redux/", 
    "previewImg":"https://media-exp1.licdn.com/dms/image/C4D12AQFhVVUXMCFfRg/article-cover_image-shrink_720_1280/0/1537600218280?e=1616025600&v=beta&t=GL38Ceosn9xGv9e_dFykDr2jEFvjtU1oSwnzuDexf-g", 
    "userID": "usermodel", 
    "category": ["frontend"], 
    "rating": "4.6", 
    "num_rating": 102.797,
    "num_views": 349.813, 
    "paid": "paid", 
    "description":"Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!", 
    "edited": "false", 
    "deleted": "false", 
    "comments": []
    
},
{
    "title":"REST Client Extension", 
    "link": "https://marketplace.visualstudio.com/items?itemName=humao.rest-client", 
    "previewImg":"https://humao.gallerycdn.vsassets.io/extensions/humao/rest-client/0.24.4/1604923740596/Microsoft.VisualStudio.Services.Icons.Default", 
    "userID": "usermodel", 
    "category": ["backend"], 
    "rating": 5, 
    "num_rating": 250,
    "num_views": 1374.560, 
    "paid": "free", 
    "description":"REST Client allows you to send HTTP request and view the response in Visual Studio Code directly.", 
    "edited": "false", 
    "deleted": "false", 
    "comments": []
    
},
{
    "title":"Mongoose", 
    "link": "https://mongoosejs.com/", 
    "previewImg":"https://niralar.com/wp-content/uploads/2018/07/mongoose.jpg", 
    "userID": "usermodel", 
    "category": ["database"], 
    "rating": 5, 
    "num_rating": 3500,
    "num_views": 1384.745, 
    "paid": "free", 
    "description":"Mongoose is a MongoDB object modeling tool designed to work in an asynchronous environment. Mongoose supports both promises and callbacks.", 
    "edited": "false", 
    "deleted": "false", 
    "comments": []
    
}, 
{
    "title":"Lodash", 
    "link": "https://lodash.com/", 
    "previewImg":"http://blog.avarteq.com/wp-content/uploads/2016/02/Lodash.jpg", 
    "userID": "usermodel", 
    "category": ["backend"], 
    "rating": 4.5, 
    "num_rating": 137,
    "num_views": 0, 
    "paid": "free", 
    "description":"Lodash makes JavaScript easier by taking the hassle out of working with arrays, numbers, objects, strings, etc. Lodash s modular methods are great for: - Iterating arrays, objects, & strings,Manipulating & testing values, Creating composite functions", 
    "edited": "false", 
    "deleted": "false", 
    "comments": []
    
},

{
    "title":"Faker.js", 
    "link": "https://github.com/Marak/Faker.js#readme", 
    "previewImg":"https://raw.githubusercontent.com/Marak/faker.js/master/logo.png", 
    "userID": "usermodel", 
    "category": ["backend"], 
    "rating": 4, 
    "num_rating": 437,
    "num_views": 112.394, 
    "paid": "free", 
    "description":"Generates massive amounts of realistic fake data in Node.js and the browser", 
    "edited": "false", 
    "deleted": "false", 
    "comments": []
    
},
{
    "title":"Guide to use GitHub Pages", 
    "link": "https://www.thinkful.com/learn/a-guide-to-using-github-pages/", 
    "previewImg":"https://i.ytimg.com/vi/2MsN8gpT6jY/maxresdefault.jpg", 
    "userID": "usermodel", 
    "category": ["general"], 
    "rating": 4.5, 
    "num_rating": 782,
    "num_views": 10.523, 
    "paid": "free", 
    "description":"Are you learning to code and need an easy, free way to host your projects? GitHub pages is your answer. Not only is it an easy hosting solution for websites with HTML, CSS, and JavaScript files, but it also gives you practice using Git, an important but tricky tool. This step-by-step guide gets you up to speed in minutes.", 
    "edited": "false", 
    "deleted": "false", 
    "comments": []
   
},
{
    "title":"Git--fast-version-control", 
    "link": "https://git-scm.com/about", 
    "previewImg":"https://git-scm.com/images/logo@2x.png", 
    "userID": "usermodel", 
    "category": ["general"], 
    "rating": 4, 
    "num_rating": 852,
    "num_views": 11.529, 
    "paid": "free", 
    "description":"This site teaches you how to use Git. It is open source and maintained by members of the Git community. We welcome patches, suggestions, and corrections.", 
    "edited": "false", 
    "deleted": "false", 
    "comments": []
   
},
{
    "title":"JWT Authentication Tutorial - Node.js", 
    "link": "https://www.youtube.com/watch?v=mbsmsi7l3r4&ab_channel=WebDevSimplified", 
    "previewImg":"https://git-scm.com/images/logo@2x.png", 
    "userID": "usermodel", 
    "category": ["backend", "frontend"], 
    "rating": 4.5, 
    "num_rating": 15985,
    "num_views": 1589.253, 
    "paid": "free", 
    "description":"How to generate 64bit secret key in the terminal and other useful things in this video", 
    "edited": "false", 
    "deleted": "false", 
    "comments": []
   
},
{
    "title":"How to access HTTP Cookie in Node.js ?", 
    "link": "https://www.geeksforgeeks.org/how-to-access-http-cookie-in-node-js/", 
    "previewImg":"https://res.cloudinary.com/practicaldev/image/fetch/s--qWK2FkdC--/c_imagga_scale,f_auto,fl_progressive,h_900,q_auto,w_1600/https://thepracticaldev.s3.amazonaws.com/i/dr6e3at3dlznretj460y.jpeg", 
    "userID": "usermodel", 
    "category": ["backend", "frontend", "database"], 
    "rating": 4, 
    "num_rating": 8951,
    "num_views": 0, 
    "paid": "free", 
    "description":"Cookies are small data that are stored on a client-side and sent to the client along with server requests. With the help of the cookie-parser module, we can do set the cookies as well as get the cookies", 
    "edited": "false", 
    "deleted": "false", 
    "comments": []
   
},
{
    "title":"Cookies", 
    "link": "https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies", 
    "previewImg":"https://res.cloudinary.com/practicaldev/image/fetch/s--qWK2FkdC--/c_imagga_scale,f_auto,fl_progressive,h_900,q_auto,w_1600/https://thepracticaldev.s3.amazonaws.com/i/dr6e3at3dlznretj460y.jpeg", 
    "userID": "usermodel", 
    "category": ["backend", "frontend", "database"], 
    "rating": 4.5, 
    "num_rating": 11.152,
    "num_views": 0, 
    "paid": "free", 
    "description":"Enables extensions to get and set cookies, and be notified when they change. To use this API, you need to include the cookies API permission in your manifest.json file, as well as host permissions for the sites whose cookies you need to access. See cookie Permissions. ", 
    "edited": "false", 
    "deleted": "false", 
    "comments": []
   
},
{
    "title":"Angular - The Complete Guide (2021 Edition)", 
    "link": "https://www.udemy.com/course/the-complete-guide-to-angular-2/", 
    "previewImg":"hhttps://appdesign.dev/wp-content/uploads/2020/08/Agencia-desarrollo-Angular-JS.jpg", 
    "userID": "usermodel", 
    "category": ["frontend"], 
    "rating": 4.6, 
    "num_rating": 138.647,
    "num_views": 459.039, 
    "paid": "paid", 
    "description":" With this course you are going to Develop modern, complex, responsive and scalable web applications with Angular 11 Fully understand the architecture behind an Angular application and how to use it ", 
    "edited": "false", 
    "deleted": "false", 
    "comments": []
   
},
{
    "title":"JavaScript, jQuery, and JSON", 
    "link": "https://www.coursera.org/learn/javascript-jquery-json?", 
    "previewImg":"https://cdn-images-1.medium.com/max/285/1*QR2SBNwG75LyY5uwqWpN3A.png", 
    "userID": "usermodel", 
    "category": ["frontend", "backend"], 
    "rating": 4.6, 
    "num_rating": 623,
    "num_views": 72.447, 
    "paid": "paid", 
    "description":" n this course, we'll look at the JavaScript language, and how it supports the Object-Oriented pattern, with a focus on the unique aspect of how JavaScript approaches OO. We'll explore a brief introduction to the jQuery library, which is widely used to do in-browser manipulation of the Document Object Model (DOM) and event handling. You'll also learn more about JavaScript Object Notation (JSON), which is commonly used as a syntax to exchange data between code running on the server (i.e. in PHP) and code running in the browser (JavaScript/jQuery).", 
    "edited": "false", 
    "deleted": "false", 
    "comments": []
   
},
// try adding throught Browser
{
    "title":"Introduction to MongoDB", 
    "link": "https://www.coursera.org/learn/introduction-mongodb?", 
    "previewImg":"https://i.pcmag.com/imagery/reviews/02Q6yxveinggAu3PomearaV-7..1569481734.jpg", 
    "userID": "usermodel", 
    "category": ["database"], 
    "rating": 4.3, 
    "num_rating": 524,
    "num_views": 41.946, 
    "paid": "free", 
    "description":"This course will get you up and running with MongoDB quickly, and teach you how to leverage its power for data analytics. We'll start by mastering the fundamentals of MongoDB, including MongoDB’s Document data model, importing data into a cluster, working with our CRUD API and Aggregation Framework. These topics will be taught through a demo application which will give you a great first encounter of how simple and practical it can be to build applications with MongoDB.In addition to these essential topics, you will also learn and work with useful MongoDB tools and services. You will work with Atlas, MongoDB's database as a service, MongoDB Compass, a schema visualization tool, as well as many other useful command-line utilities.", 
    "edited": "false", 
    "deleted": "false", 
    "comments": []
   
},
